# Generated by Django 6.0.4 on 2026-06-12 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='event_date',
            field=models.DateField(),
        ),
    ]
